name:                path-utils
version:             0.1.1.0
git:                 https://gitlab.com/homotopic-tech/path-utils
license:             MIT
author:              "Daniel Firth"
maintainer:          "dan.firth@homotopic.tech"
copyright:           "2020 Daniel Firth"

extra-source-files:
- README.md
- ChangeLog.md

synopsis:            Handful of simple utility functions for the path library.
category:            Filesystem
description:         Handful of simple utility functiosn for the path library.

dependencies:
- base >= 4.7 && < 5
- exceptions
- path
- split
- text

ghc-options:
- -Wall
- -Wcompat
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wredundant-constraints

library:
  source-dirs: src
